### ISSUE TITLE
issue with resolving internal links when used with myst_parser

### ISSUE THREAD

**Issue by noname77** [rogerbarton/sphinx-csharp#12]
Hi

I started moving from rst to MyST recently to be able to write documentation in markdown and I'm getting errors while resolving internal references in `[description](link)` format, i.e. when linking to a header within a document `[mobile](#mobile)`:

```
<PROJECT_PATH>/index.md:10: WARNING: Failed to find xref for: #mobile, no objects found that end like this, searched in object types: ['enumerator']

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.8/site-packages/myst_parser/sphinx_ext/myst_refs.py", line 147, in resolve_myst_ref
    domain.resolve_any_xref(
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx_csharp/csharp.py", line 1031, in resolve_any_xref
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build_update
    self.build(to_build,
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 377, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 579, in write
    self._write_serial(sorted(docnames))
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 586, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 622, in get_and_resolve_doctree
    self.apply_post_transforms(doctree, docname)
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/environment/__init__.py", line 668, in apply_post_transforms
    transformer.apply_transforms()
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 80, in apply_transforms
    super().apply_transforms()
  File "/home/vscode/.local/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 173, in apply_transforms
    transform.apply(**kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx/transforms/post_transforms/__init__.py", line 37, in apply
    self.run(**kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/myst_parser/sphinx_ext/myst_refs.py", line 52, in run
    newnode = self.resolve_myst_ref(refdoc, node, contnode)
  File "/home/vscode/.local/lib/python3.8/site-packages/myst_parser/sphinx_ext/myst_refs.py", line 163, in resolve_myst_ref
    res = domain.resolve_xref(
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx_csharp/csharp.py", line 915, in resolve_xref
    objects = {
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx_csharp/csharp.py", line 919, in <dictcomp>
    if key[0] in objtypes and key[1].endswith(target) and
TypeError: argument of type 'NoneType' is not iterable

Exception occurred:
  File "/home/vscode/.local/lib/python3.8/site-packages/sphinx_csharp/csharp.py", line 919, in <dictcomp>
    if key[0] in objtypes and key[1].endswith(target) and
TypeError: argument of type 'NoneType' is not iterable
```

I added a debug print in csharp.py -> CSharpDomain.resolve_xref, which shows
```
target: #mobile, node: {'rawsource': '', 'children': [<inline: <#text: 'mobile'>>], 'attributes': {'ids': [], 'classes': [], 'names': [], 'dupnames': [], 'backrefs': [], 'refdoc': 'index', 'reftarget': '#mobile', 'reftype': 'myst', 'refdomain': None, 'refexplicit': True, 'refwarn': True}, 'tagname': 'pending_xref', 'line': 10, 'source': '<PROJECT_PATH>/index.md', 'parent': <paragraph: <#text: 'redacted ...'><pending_xref...><#text: '  ...>, '_document': <document: <section "redacted"...>>}
```

Modifying `resolve_xref` like so seems to fix the issue
```
    def resolve_xref(self, _, fromdocname, builder, typ, target, node, contnode):
        targets = []
        parents = []

        if node.attributes["refdomain"] != self.name:
            return None

        # rest of resolve_xref unchanged
```

Any chance you could include this in your releases?

Best,
Wiktor

**Comment by rogerbarton** [comment]
Apologies for the inactivity on my behalf. It seems strange that the C# domain is being called for a normal link, the edit in #14 makes sense though.
